### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by andy-westacott** [NordSecurity/uniffi-bindgen-cpp#10]
Hi

I'm interested in making use of this project but I'm having a couple of issues.

I'm generating the bindings from a simple project but when I copy over the generated files to my C++ project and building as you mention in the readme.  I have a bunch of missing symbols.  I can see them declared in xxx_scaffolding.hpp file and they are referenced in the xxx.cpp file but no idea where the implementation of these is supposed to be.

For example
1>math.obj : error LNK2019: unresolved external symbol uniffi_xxx_fn_func_my_add referenced in function "int __cdecl math::my_add(int,int)" (?my_add@math@@YAHHH@Z)
1>math.obj : error LNK2019: unresolved external symbol ffi_xxx_rustbuffer_alloc referenced in function "struct RustBuffer __cdecl math::uniffi::rustbuffer_alloc(int)" (?rustbuffer_alloc@uniffi@math@@YA?AURustBuffer@@H@Z)
1>math.obj : error LNK2019: unresolved external symbol ffi_xxx_rustbuffer_from_bytes referenced in function "struct RustBuffer __cdecl math::uniffi::rustbuffer_from_bytes(struct ForeignBytes const &)" (?rustbuffer_from_bytes@uniffi@math@@YA?AURustBuffer@@AEBUForeignBytes@@@Z)
1>math.obj : error LNK2019: unresolved external symbol ffi_xxx_rustbuffer_free referenced in function "void __cdecl math::uniffi::rustbuffer_free(struct RustBuffer)" (?rustbuffer_free@uniffi@math@@YAXURustBuffer@@@Z)

Any thoughts or some more information on what I'm supposed to implement?

I'm using Visual C++ on Windows for this.

Thanks

**Comment by Lipt0nas** [comment]
Hey

Are you linking the built Rust library in addition to the generated `.hpp`/`.cpp` code?

**Comment by andy-westacott** [comment]
Hmm I was linking to A library.... just not the right one.  Dumb mistake on
my part. Sorry

**Comment by Lipt0nas** [comment]
No problem, let me know if linking the correct library fixes the issue

**Comment by andy-westacott** [comment]
yep looking good.

Thank you.
