### ISSUE TITLE
Plan to support procedural macros bindings?

### ISSUE THREAD

**Issue by RCasatta** [NordSecurity/uniffi-bindgen-cpp#18]
I am using procedural macros https://mozilla.github.io/uniffi-rs/proc_macro/index.html to generate bindings for my project so I haven't an udl file, are there any plan to support this?

thanks

**Comment by Lipt0nas** [comment]
Hey,

`uniffi-bindgen-cpp` supports library mode needed to generate the bindings, you can use
`./uniffi-bindgen-cpp --library your_rust_library.so --out-dir output_directory` for this

the docs will also be updated to inform of this
