### ISSUE TITLE
value: ExtendedAttributeNoArgs not supported: "WithForeign"

### ISSUE THREAD

**Issue by theashraf** [NordSecurity/uniffi-bindgen-cpp#21]
I'm getting this error when using uniffi-bindgen-cpp `v0.3.0+v0.25.0` with uniffi-rs `v0.26.0`

```
uniffi-bindgen-cpp --config dotlottie-ffi/uniffi.toml --out-dir dotlottie-ffi/uniffi-bindings/cpp dotlottie-ffi/src/dotlottie_player.udl
thread 'main' panicked at bindgen/src/main.rs:44:10:
called `Result::unwrap()` on an `Err` value: ExtendedAttributeNoArgs not supported: "WithForeign"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [dotlottie-ffi/uniffi-bindings/cpp] Error 101
```

.udl
```
namespace dotlottie_player {
};

[Trait, WithForeign]
interface Observer {
    void on_play();
    void on_pause();
    void on_stop();
};
```

**Comment by Lipt0nas** [comment]
uniffi-bindgen-cpp is currently supposed to be used with uniffi-rs `v0.25.0` only, the `WithForeign` attribute is a feature of uniffi-rs `v0.26.0`

uniffi-bindgen-cpp uses tag naming convention as follows: vX.Y.Z+vA.B.C, where X.Y.Z is the version of the generator itself, and A.B.C is the version of uniffi-rs it is based on

**Comment by theashraf** [comment]
Thank you, @Lipt0nas!
Do you have any plans to support future releases of uniffi-rs?

**Comment by Lipt0nas** [comment]
Glad to help!
Sadly we currently do not have plans to update the supported uniffi-rs version
