### ISSUE TITLE
Invalid generated code for allocation_size for empty record

### ISSUE THREAD

**Issue by artemyarulin** [NordSecurity/uniffi-bindgen-cpp#45]
For the UDL
```
namespace A {};
dictionary B {};
```
If I run a latest released  generator (v0.6.2+v0.25.0) `uniffi-bindgen-cpp foo.udl --out-dir build` it will create a `A.cpp` with this code at end end 
```C++
void FfiConverterTypeB::write(RustStream &stream, const B &val) {
}

int32_t FfiConverterTypeB::allocation_size(const B &val) {
    return 
}

}} // namespace A
```

Notice missing value after `return` for `allocation_size`. 

I'm not sure how generator works, but my guess it's because template iterates through all the fields and if there are none then there is no fallback value:

https://github.com/NordSecurity/uniffi-bindgen-cpp/blob/1521029d442d9b747102629c2fe817e7b6b241a4/bindgen/src/bindings/cpp/templates/rec.cpp#L35-L39

**Comment by Lipt0nas** [comment]
Hey! sorry for the late reply, could you give the branch a try to see if it works as expected?

**Comment by artemyarulin** [comment]
Yeah, that solves it - thanks a lot!

**Comment by Lipt0nas** [comment]
Nice! I'll make a new tag with the changes then
